apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  MICROSERVICE1: http://microservice-1:3001
  MICROSERVICE2: http://microservice-2:3002
  MICROSERVICE3: http://microservice-3:3003
  MICROSERVICE4: http://microservice-4:3004
  MICROSERVICE5: http://microservice-5:3005
  MICROSERVICE6: http://microservice-6:3006