{{- range .Values.microservices}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" .name }}
  labels:
    {{- include "microservices.labels" (dict "Chart" $.Chart "Release" $.Release "Values" .) | nindent 4 }}
    {{- with .labels}}
    {{- toYaml . | nindent 4}}
    {{- end}}
spec:
  type: {{ .type | default "ClusterIP"}}
  ports:
    - port: {{ .ports.containerPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- with .labels}}
    {{- toYaml . | nindent 4}}
    {{- end}}
{{- end}}
